title: "Engine Beast : Alpha"
description: "Main Page"

markdown: kramdown

highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

defaults:
  - scope:
      path: "" 
    values:
      title: "Engine Beast : Alpha"

comments:
  active: 'giscus'
  giscus:
    repo: "enginebeast/enginebeast.github.io"
    repo_id: "R_kgDOPCKDlA"
    category: "[ENTER CATEGORY NAME HERE]"
    category_id: "[ENTER CATEGORY ID HERE]"

theme: jekyll-theme-cayman
