title: "Engine Beast : Alpha"
description: "Main Page"

# Fixiing the title
defaults:
  - scope:
      path: "" 
    values:
      title: "Engine Beast : Alpha"

# Fixing and simplifying the form of url
permalink: /:title/

# Archives
math_note_archive:
  type: liquid
  path: /math_note/
physics_note_archive:
  type: liquid
  path: /physics_note/
eee_note_archive:
  type: liquid
  path: /eee_note/
smallcar_archive:
  type: liquid
  path: /smallcar/

# Code for maxjax
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

theme: jekyll-theme-cayman
