title: "Engine Beast : Alpha"
description: "Main Page"

markdown: kramdown
kramdown:
mathengine: mathjax

highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
theme: jekyll-theme-cayman
